FROM python:3.10-slim

WORKDIR app/

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY src/__init__.py src/__init__.py
COPY src/apis src/apis
COPY src/pipelines src/pipelines

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "src.pipelines.run_finance"]
