FROM python:3.10-slim

WORKDIR app/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/__init__.py src/__init__.py
COPY src/apis src/apis

COPY main2.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "src.apis.apis.finance.app"]
