services:

  finance-api:
    build:
      context: .
      dockerfile: Dockerfile-finance-api
    ports:
      - "5001:5001"

  finance-pipeline:
    build:
      context: .
      dockerfile: Dockerfile-finance-pipeline

    env_file:
      - .env

    depends_on:
      - finance-api