services:

  postgres-users:
    build:
      context: infra/postgres/users
      dockerfile: Dockerfile
    container_name: postgres-users
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres_users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PORT=5432
    volumes:
      - postgres_users_data:/var/lib/postgresql/data

  finance-api:
    build:
      context: .
      dockerfile: Dockerfile-finance-api
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app

  finance-pipeline:
    build:
      context: .
      dockerfile: Dockerfile-finance-pipeline

    environment:
      - FINANCE_PIPELINE_BASE_URL=http://finance-api:5001

    env_file:
      - .env

    depends_on:
      - finance-api

    volumes:
      - .:/app
volumes:
  postgres_users_data: